### ISSUE TITLE
Enable dark theme by default?

### ISSUE THREAD

**Issue by beverloo** [AnimeNL/portal#16]
Dark theme is currently internal-only through a `kEnableDarkTheme` setting in `config.tsx`. It would be great to enable it by default, but we'll need to run through the appearance of.. everything and make sure there are appropriate colours.

The main thing I'm worried about is contrast. Particularly on pages listing past, active and future event sessions, the colours distinguishing them from each other are really similar. Perhaps we can come up with some clearer ways of doing that?

**Comment by beverloo** [comment]
@fuegas added a new colour in 0be45fb that I agree looks better. I'd still want to give the entire page a think-over since the contrast differences are very low.

**Comment by fuegas** [comment]
Yeah, I've looked at various dark themes the past few days and all of them have the issue of low contrast 🤔 So this is going to be a nice challenge. When I try to change some settings I check them in a bright room and a (very) dark room (with low brightness on my phone) to see the impact. It's not easy to keep it readable and enough contrast if you switch between these.
