### ISSUE TITLE
Error: Unable to access the event when there is none available.

### ISSUE THREAD

**Issue by coderiekelt** [AnimeNL/portal#26]
This issue seems to be caused when the type of a shift is an Event, but the event itself is not set on the shift, this causes a white page and the following error message:
```
Error: Unable to access the event when there is none available. Shift.tsx:75:18
    get event Shift.tsx:75
    getDerivedStateFromProps VolunteerSchedulePage.tsx:102
    React 10
    Tn self-hosted:1029
Error: "Unable to access the event when there is none available."
    get event Shift.tsx:75
    getDerivedStateFromProps VolunteerSchedulePage.tsx:102
    React 10
```

Seems to be localized to at least my schedule, and maybe a few others. (other schedules are visible just fine).

The isEvent could possibly check if the event itself is also set?

**Comment by fuegas** [comment]
Thanks for the bugreport. I've added some more debugging information for us in fb61897, but I've already pinpointed the shift that causes this error. You'll hear more from us soon.

**Comment by beverloo** [comment]
Fixed with:
https://github.com/AnimeNL/anime-2017/commit/f143ee14861fa296ec157a82fe4a1aded0470eb3
https://github.com/AnimeNL/anime-2017/commit/460d46c8bd8c900f0aaa8730d70950a746e6132b
